Repository Coden-inja/alchEmaiLyst, pull requests merged in 2025-08, with the labels that each got.

#25 Create CodeOfConduct.md
  CodeOfConduct.md
Labels: documentation, Level 1, gssoc25

#47 Added MIT License link to README
  README.md
Labels: documentation, Level 1, gssoc25

#50 Enhance AI Email Composition for proper structured Output
  src/components/Dashboard.tsx
Labels: gssoc25

#62 Add Standardised Templates for Pull Requests and Issues
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/performance.md
  .github/pull_request_template.md
Labels: documentation, OSCI'25, 2⭐⭐

#73 Removed Div which was overriding to Main content.
  src/components/Hero.tsx
Labels: bug, Level 1, gssoc25

#79 issue create automate message added
  .github/workflows/issue-create-automate-message.yml
Labels: enhancement, OSCI'25, 2⭐⭐
